
# 服务端口号
server:
  port: 10001

spring:
  # 应用名
  application:
    name: eureka


eureka:
  client:
    service-url:        # Eureka Server的分区地址
      defaultZone: http://user:123456@eureka2:10002/eureka/,http://user:123456@eureka3:10003/eureka/
    fetch-registry: true         # 是否从其他的服务中心同步服务列表   集群需要设置为true
    register-with-eureka: true     # 是否把自己作为服务注册到其他服务注册中心 集群需要设置为true
  server:
    eviction-interval-timer-in-ms: 5000    # 设置清理服务的间隔时间ms  默认60秒
    use-read-only-response-cache: false     # 此处不开启缓存
    enable-self-preservation: false     # 自我保护机制
  instance:
    prefer-ip-address: false     # 是否优先显示ip eureka集群设置为false
    instance-id: eureka-one   # eureka实例ID  不可重复
    hostname: eureka1   # 主机名 不能重复

