
# 服务端口号
server:
  port: 10003

spring:
  # 应用名
  application:
    name: eureka


eureka:
  client:
    service-url:        # Eureka Server的分区地址
      defaultZone: http://user:123456@eureka1:10001/eureka/,http://user:123456@eureka2:10001/eureka/
    fetch-registry: true         # 是否从其他的服务中心同步服务列表
    register-with-eureka: true     # 是否把自己作为服务注册到其他服务注册中心
  server:
    eviction-interval-timer-in-ms: 5000    # 设置清理服务的间隔时间ms  默认60秒
    use-read-only-response-cache: false     # 此处不开启缓存
    enable-self-preservation: false     # 自我保护机制
  instance:
    prefer-ip-address: false     # 是否优先显示ip
    instance-id: eureka-three   # eureka实例ID
    hostname: eureka3   # 主机名 不能重复

